/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.animalerie.view;

import fr.ufrsciencestech.animalerie.User;
import fr.ufrsciencestech.animalerie.Animal;
import fr.ufrsciencestech.animalerie.controleur.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author delaton
 */
public class AjoutAnimalView extends javax.swing.JFrame {
    /**
     * Creates new form AjoutAnimalView
     */
    public AjoutAnimalView() {
        initComponents();
        btAnnuler.setName("Annuler");
        btConfirmer.setName("Confirmer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEspece = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPoids = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btConfirmer = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter un animal");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nom : ");
        jPanel1.add(jLabel2);

        jNom.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jNom);

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Espèce : ");
        jPanel1.add(jLabel3);

        jEspece.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jEspece.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jEspece);

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Age : ");
        jPanel1.add(jLabel4);

        jAge.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jAge);

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Poids : ");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);

        jPoids.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jPoids.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jPoids);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btConfirmer.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btConfirmer.setText("Ajouter");
        btAnnuler.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btAnnuler.setText("Annuler");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btConfirmer))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>                        

                
    public JTextField getAge() { return this.jAge; }
    public JTextField getNom() { return this.jNom; }
    public JTextField getEspece() { return this.jEspece; }
    public JTextField getPoids() { return this.jPoids; }
    
    public void ajoutControleur(Controleur c)
    {
        this.btConfirmer.addActionListener(c);
    }
    
    public void showMessage(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btConfirmer;
    private javax.swing.JTextField jAge;
    private javax.swing.JTextField jEspece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPoids;
    // End of variables declaration                   
}
