/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.animalerie.view;

import fr.ufrsciencestech.animalerie.controleur.Controleur;
import java.awt.Component;
import javax.swing.*;

/**
 *
 * @author delaton
 */
public class ProduitView extends javax.swing.JFrame {

    /**
     * Creates new form ProduitView
     */
    public ProduitView() {
        initComponents();
        btConfirmer.setName("btConfirmer");
        btAnnuler.setName("btAnnuler");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btAccess = new javax.swing.JRadioButton();
        btMed = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jAccess = new javax.swing.JComboBox<>();
        jMed = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jQuantite = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btConfirmer = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Achat d'un produit");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        buttonGroup1.add(btAccess);
        btAccess.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        btAccess.setSelected(true);
        btAccess.setText("Accessoires");
        btAccess.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btAccess.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccessActionPerformed(evt);
            }
        });
        jPanel3.add(btAccess);

        buttonGroup1.add(btMed);
        btMed.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        btMed.setText("Médicaments");
        btMed.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btMed.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedActionPerformed(evt);
            }
        });
        jPanel3.add(btMed);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jAccess.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jAccess.setMaximumRowCount(70);
        jAccess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coussin/Lit", "Niche (pour chien)", "Cage (pour oiseaux/rongeurs)", "Caisse de transport", "Brosse et peigne", "Shampoings", "Litières", "Balles (pour chien/chat)", "Corde à macher (pour chien/chat)", "Perchoir (pour oiseaux)", "Collier et harnais", "Laisse de dressage", " " }));
        jPanel4.add(jAccess);

        jMed.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jMed.setMaximumRowCount(80);
        jMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amoxiciline (Antibiotiques)", "Colliers antiparasitaires (Antiparasitaire)", "Métacam (Anti-inflammatoires) pour chien/chat", "Insuline pour chien/chat", "Benadryl (Antihistaminiques)", "Kétoconazole (Antifongiques)", "Kaolin-Pectine (Anti-diarrhéiques) pour chien/chat", "Glucosamine (Suppléments articulaires)", "Oméga-3 (Suppléments articulaires)" }));
        jMed.setEnabled(false);
        jPanel4.add(jMed);

        jPanel1.add(jPanel4);

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel2.setText("Quantité -------->");

        jQuantite.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jQuantite.setMaximumRowCount(5);
        jQuantite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btConfirmer.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btConfirmer.setText("Ajouter");
        

        btAnnuler.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btAnnuler.setText("Annuler");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btConfirmer))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>                        
                                  

    private void btMedActionPerformed(java.awt.event.ActionEvent evt) {                                      
        jAccess.setEnabled(false);
        jMed.setEnabled(true);
    }                                     

    private void btAccessActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jAccess.setEnabled(true);
        jMed.setEnabled(false);
    }                                        

    public void ajoutControleur(Controleur c)
    {
        this.btConfirmer.addActionListener(c);
        this.btAnnuler.addActionListener(c);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton btAccess;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btConfirmer;
    private javax.swing.JRadioButton btMed;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jAccess;
    private javax.swing.JComboBox<String> jQuantite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jMed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration                   

    public JRadioButton getBtAccess() {
        return this.btAccess;
    }

    public JComboBox<String> getjAccess() {
        return this.jAccess;
    }

    public JComboBox<String> getJQuantite() {
        return this.jQuantite;
    }

    public JComboBox<String> getjMed() {
        return this.jMed;
    }

    public void showMessage(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
}
