/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.animalerie.view;

import fr.ufrsciencestech.animalerie.controleur.Controleur;
import fr.ufrsciencestech.animalerie.controleur.ControleurConnexion;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author delaton
 */
public class UserInscription extends javax.swing.JFrame {

    /**
     * Creates new form UserInscription
     */
    public UserInscription() {
        initComponents();
        btConnexion.setName("ViewConnexion");
        btQuit.setName("Quit");
        btBInscription.setName("Inscription");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jNom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMotdePasse = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        btConnexion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btBInscription = new javax.swing.JButton();
        btQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inscription");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(10, 1));

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nom :");
        jPanel1.add(jLabel6);

        jNom.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        
        jPanel1.add(jNom);

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Prénom :");
        jPanel1.add(jLabel5);

        jPrenom.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jPrenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        
        jPanel1.add(jPrenom);

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mail :");
        jPanel1.add(jLabel4);

        jMail.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        
        jPanel1.add(jMail);

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mot de passe : ");
        jPanel1.add(jLabel2);

        jMotdePasse.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jMotdePasse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jMotdePasse);

        btConnexion.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        btConnexion.setText("Connexion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(btConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btBInscription.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btBInscription.setText("Valider");
        

        btQuit.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btQuit.setText("Quitter");
        

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuit)
                    .addComponent(btBInscription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>                        
                                  
    
    public JButton getBtconnect()
    {
        return this.btConnexion;
    }
    
    public JButton getBtQuit() { return this.btQuit; }
    
    public JButton getBtInscription() { return this.btBInscription; }
    
    public JTextField jMail() { return this.jMail; }
    
    public JTextField JPass() { return this.jMotdePasse; }
    
    public JTextField jNom() { return this.jNom; }
    
    public JTextField jPrenom() { return this.jPrenom; }
    
    public void ajoutControleur(Controleur c)
    {
        this.btConnexion.addActionListener(c);
        this.btBInscription.addActionListener(c);
        this.btQuit.addActionListener(c);
    }
    
    public void showMessage(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btBInscription;
    private javax.swing.JButton btConnexion;
    private javax.swing.JButton btQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jMail;
    private javax.swing.JTextField jMotdePasse;
    private javax.swing.JTextField jNom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPrenom;
    // End of variables declaration                   
}
