/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.animalerie.view;

import fr.ufrsciencestech.animalerie.User;
import fr.ufrsciencestech.animalerie.controleur.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author delaton
 */
public class UserConnect extends javax.swing.JFrame{
    
    private User client;

    /**
     * Creates new form UserConnect
     */
    public UserConnect() {
        initComponents();
        btConnexion.setName("Connexion");
        btQuit.setName("Quit");
        btInscription.setName("ViewInscription");
    }
    
    public void showMessage(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMotdePasse = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btInscription = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btConnexion = new javax.swing.JButton();
        btQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Connexion");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mail :");
        jPanel1.add(jLabel4);

        jMail.setFont(new java.awt.Font("DejaVu Serif", 2, 15)); // NOI18N
        jMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jMail.setToolTipText("");
        jPanel1.add(jMail);

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mot de passe : ");
        jPanel1.add(jLabel2);

        jMotdePasse.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        jMotdePasse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jMotdePasse);

        btInscription.setFont(new java.awt.Font("DejaVu Serif", 2, 16)); // NOI18N
        btInscription.setText("Inscription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(btInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btConnexion.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btConnexion.setText("Connexion");

        btQuit.setFont(new java.awt.Font("DejaVu Serif", 3, 16)); // NOI18N
        btQuit.setText("Quitter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuit)
                    .addComponent(btConnexion))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>                        
                                              
    
    public JButton getBtconnect()
    {
        return this.btConnexion;
    }
    
    public JButton getBtQuit() { return this.btQuit; }
    
    public JButton getBtInscription() { return this.btInscription; }
    
    public JTextField jMail() { return this.jMail; }
    
    public JTextField JPass() { return this.jMotdePasse; }
    
    public void ajoutControleur(Controleur c)
    {
        this.btConnexion.addActionListener(c);
        this.btInscription.addActionListener(c);
        this.btQuit.addActionListener(c);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btConnexion;
    private javax.swing.JButton btInscription;
    private javax.swing.JButton btQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jMail;
    private javax.swing.JPasswordField jMotdePasse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}
