DROP TABLE ANIMAL;
DROP TABLE SERVICE_P;
DROP TABLE PRODUIT_ACHETER;
DROP TABLE PRODUIT_STOCK;
DROP TABLE COMMANDE;
DROP TABLE RESERVATION;
DROP TABLE CLIENT;



CREATE TABLE CLIENT
(
    id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar2(100),
    prenom varchar2(100),
    mail varchar2(100) UNIQUE,
    mot_de_passe varchar2(100) 
);

CREATE TABLE ANIMAL
(
    id_animal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_a varchar(15),
    poids float,
    age integer,
    espece varchar(20),
    id_client REFERENCES CLIENT (id_client) INITIALLY DEFERRED DEFERRABLE
);


CREATE TABLE COMMANDE
(
    id_commande integer PRIMARY KEY,
    statut_c varchar(10) CONSTRAINT valeur_permise_pour_statut_c CHECK (statut_c IN ('EN_ATTENTE', 'CONFIRMÉE')),
    id_client NOT NULL REFERENCES CLIENT (id_client) INITIALLY DEFERRED DEFERRABLE
);

CREATE TABLE RESERVATION
(
    id_reservation integer PRIMARY KEY,
    statut_r varchar(10) CONSTRAINT valeur_permise_pour_statut_r CHECK (statut_r IN ('EN_ATTENTE', 'CONFIRMÉE')),
    date_r date NOT NULL,
    id_client NOT NULL REFERENCES CLIENT (id_client) INITIALLY DEFERRED DEFERRABLE
);

CREATE TABLE PRODUIT_STOCK
(
    id_produit integer PRIMARY KEY,
    type_produit varchar(15) CONSTRAINT valeur_permise_pour_type_p CHECK (type_produit IN ('Accessoire', 'Médicament')),
    nom_p varchar(100),
    stock integer,
    prix_p float
);

CREATE TABLE SERVICE_P
(
    id_service NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_s varchar(18) CONSTRAINT valeur_permise_pour_service CHECK (nom_s IN ('Promenade' , 'Garde' , 'Toilettage', 'Education Canine')),
    prix_s float,
    duree varchar(150),
    descr varchar(150),
    id_reservation REFERENCES RESERVATION (id_reservation) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE
);


CREATE TABLE PRODUIT_ACHETER
(
    id_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_p varchar(100),
    qteChoisie integer,
    prix_p float,
    id_commande REFERENCES COMMANDE (id_commande) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE
);

INSERT INTO PRODUIT_STOCK VALUES(1, 'Accessoire', 'Coussin/Lit', 10, 10.0);
INSERT INTO PRODUIT_STOCK VALUES(2, 'Accessoire', 'Niche (pour chien)', 10, 8.0);
INSERT INTO PRODUIT_STOCK VALUES(3, 'Accessoire', 'Cage (pour oiseaux/rongueurs)', 10, 6.0);
INSERT INTO PRODUIT_STOCK VALUES(4, 'Accessoire', 'Caisse de transport', 10, 15.0);
INSERT INTO PRODUIT_STOCK VALUES(5, 'Accessoire', 'Brosse et peigne', 10, 5.0);
INSERT INTO PRODUIT_STOCK VALUES(6, 'Accessoire', 'Shampoings', 10, 4.5);
INSERT INTO PRODUIT_STOCK VALUES(7, 'Accessoire', 'Litières', 10, 5.0);
INSERT INTO PRODUIT_STOCK VALUES(8, 'Accessoire', 'Balles (pour chien/chat)', 10, 2.0);
INSERT INTO PRODUIT_STOCK VALUES(9, 'Accessoire', 'Corde à macher (pour chien/chat)', 10, 3.0);
INSERT INTO PRODUIT_STOCK VALUES(10, 'Accessoire', 'Perchoir (pour oiseaux)', 10, 9.5);
INSERT INTO PRODUIT_STOCK VALUES(11, 'Accessoire', 'Collier et harnais', 10, 10.0);
INSERT INTO PRODUIT_STOCK VALUES(12, 'Accessoire', 'Laisse de dressage', 10, 6.0);

INSERT INTO PRODUIT_STOCK VALUES(13, 'Médicament', 'Amoxiciline (Antibiotiques)', 10, 20.0);
INSERT INTO PRODUIT_STOCK VALUES(14, 'Médicament', 'Colliers antiparasitaires (Antiparasitaire)', 5, 10.0);
INSERT INTO PRODUIT_STOCK VALUES(15, 'Médicament', 'Métacam (Anti-inflammatoires) pour chien/chat', 5, 12.0);
INSERT INTO PRODUIT_STOCK VALUES(16, 'Médicament', 'Insuline pour chien/chat', 10, 18.0);
INSERT INTO PRODUIT_STOCK VALUES(17, 'Médicament', 'Benadryl (Antihistaminiques)', 10, 14.0);
INSERT INTO PRODUIT_STOCK VALUES(18, 'Médicament', 'Kétoconazole (Antifongiques)', 10, 30.0);
INSERT INTO PRODUIT_STOCK VALUES(19, 'Médicament', 'Kaolin-Pectine (Anti-diarrhéiques) pour chien/chat', 10, 15.0);
INSERT INTO PRODUIT_STOCK VALUES(20, 'Médicament', 'Glucosamine (Suppléments articulaires)', 10, 10.0);
INSERT INTO PRODUIT_STOCK VALUES(21, 'Médicament', 'Oméga-3 (Suppléments articulaires)', 10, 12.0);

